version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - cellulardensity

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cellulardensity

networks:
  cellulardensity:

